"""Added new models

Revision ID: 3df89a4479b5
Revises: d1b9c695dc9f
Create Date: 2024-08-16 17:40:26.376509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df89a4479b5'
down_revision = 'd1b9c695dc9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_complexity_quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=False),
    sa.Column('correct_complexity', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_guess', sa.String(length=50), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forum_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coding_problem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solved', sa.Boolean(), nullable=True))

    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=50), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('problems_solved', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_complexity_quizzes_correct', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('time_complexity_quizzes_correct')
        batch_op.drop_column('problems_solved')
        batch_op.drop_column('correct_answers')

    with op.batch_alter_table('flashcard', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('coding_problem', schema=None) as batch_op:
        batch_op.drop_column('solved')

    op.drop_table('forum_reply')
    op.drop_table('time_complexity_quiz')
    op.drop_table('forum_post')
    # ### end Alembic commands ###
